version: '3'
services:
  express-app:
    build:
      context: ./
    ports:
      - "6000:5000"
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
    privileged: true
    depends_on:
      - express-app